// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate/seed/db:push ใช้ direct connection (port 5432) เลี่ยง pgbouncer
    // ถ้าไม่มี DIRECT_URL ใช้ DATABASE_URL แทน
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
